

export { default as AGS } from '../../images/clientes/AGS.png'
export { default as ALSA } from '../../images/clientes/ALSA.png'
export { default as Arbolandia } from '../../images/clientes/ARBOLANDIA.png'
export { default as CCERM } from '../../images/clientes/CCERM.png'
export { default as Chijaj } from '../../images/clientes/CHIIJAJ.png'
export { default as ColegioPlayaDelCarmen } from '../../images/clientes/COLEGIO-PLAYA-DEL-CARMEN.png'
export { default as CPCRM } from '../../images/clientes/COLEGIO-PROFESIONALES-DE-LA-CONTADURIA.png'
export { default as CongresoIbero } from '../../images/clientes/CONGRESO-IBERO.png'
export { default as DeMuerte } from '../../images/clientes/DEMUERTE.png'
export { default as FEMCIC } from '../../images/clientes/FEMCIC.png'
export { default as GobGdl } from '../../images/clientes/GOB-Guadalajara.png'
export { default as HOMEZEN } from '../../images/clientes/HOMEZEN.png'
export { default as JalicoEsMexico } from '../../images/clientes/JALISCO-ES-MEXICO.png'
export { default as LEMUS } from '../../images/clientes/LEMUS.png'
export { default as NacionMX } from '../../images/clientes/NACION-MX.png'
export { default as PANAJAL } from '../../images/clientes/PANAJAL.png'
export { default as TheWineCorner } from '../../images/clientes/THE-WINE-CORNER.png'
export { default as VINESP } from '../../images/clientes/VINESP.png'
export { default as WishNana } from '../../images/clientes/WISH-NANA.png'
